### ISSUE TITLE
cant run the code please help

### ISSUE THREAD

**Issue by rodgerma** [MaxSSD/age-detection-cv2#1]
Traceback (most recent call last):
  File "c:\Users\Macalalag\Documents\GitHub\age-detection-cv2\main.py", line 20, in <module>
    faceNet=cv2.dnn.readNet(faceModel, faceProto)
cv2.error: OpenCV(4.5.4) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\caffe\caffe_io.cpp:1138: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "opencv_face_detector_uint8.pb" in function 'cv::dnn::ReadProtoFromBinaryFile'

**Comment by MaxSSD** [comment]
Thanks for pointing that out! I forgot to mention the step of downloading the detection models from the [drive](https://drive.google.com/drive/folders/1d_uT8PUULb0Py0Mfn70N9N6u-peQ3P2B?usp=sharing) and putting them in the same folder as main.py.
